---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: worker-example
  namespace: test
  labels:
    sigs.k8s.io/cluster-api-cluster: cluster-name
    sigs.k8s.io/cluster-api-machine-role: infra
    sigs.k8s.io/cluster-api-machine-type: worker
spec:
  providerConfig:
    value:
      apiVersion: hyperkitproviderconfig/v1alpha1
      kind: HyperkitMachineProviderConfig
      domainMemory: 4086
      domainVcpu: 2
      ignKey: /var/lib/libvirt/images/worker.ign
      networkInterfaceName: actuatorTestNetwork
      networkInterfaceAddress: 192.168.64.0/24
      autostart: false
      hyperkitBinaryLocation: /usr/local/bin/hyperkit
  versions:
    kubelet: ""
    controlPlane: ""
