---
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineSet
metadata:
  name: worker-example-machine-set
  namespace: test
  labels:
    sigs.k8s.io/cluster-api-cluster: tb-asg-35
    sigs.k8s.io/cluster-api-machine-role: infra
    sigs.k8s.io/cluster-api-machine-type: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-machineset: worker-example-machine-set
      sigs.k8s.io/cluster-api-cluster: tb-asg-35
      sigs.k8s.io/cluster-api-machine-role: infra
      sigs.k8s.io/cluster-api-machine-type: worker
  template:
    metadata:
      labels:
        sigs.k8s.io/cluster-api-machineset: worker-example-machine-set
        sigs.k8s.io/cluster-api-cluster: tb-asg-35
        sigs.k8s.io/cluster-api-machine-role: infra
        sigs.k8s.io/cluster-api-machine-type: worker
    spec:
      providerConfig:
        value:
          apiVersion: hyperkitproviderconfig/v1alpha1
          kind: HyperkitMachineProviderConfig
          domainMemory: 2048
          domainVcpu: 1
          ignKey: /var/lib/libvirt/images/worker.ign
          networkInterfaceName: tectonic
          networkInterfaceAddress: 192.168.64.1
          autostart: false
          hyperkitBinLocation: /usr/local/bin/hyperkit
      versions:
        kubelet: ""
        controlPlane: ""
