---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: worker-example
  namespace: test
  generateName: vs-worker-
  labels:
    sigs.k8s.io/cluster-api-cluster: tb-asg-35
    sigs.k8s.io/cluster-api-machine-role: infra
    sigs.k8s.io/cluster-api-machine-type: worker
spec:
  providerConfig:
    value:
      apiVersion: hyperkitproviderconfig.k8s.io/v1alpha1
      kind: HyperkitMachineProviderConfig
      domainMemory: 2048
      domainVcpu: 2
      networkInterfaceName: default
      networkInterfaceAddress: 192.168.64.0/24
      autostart: false
      hyperkitBinaryLocation: /usr/local/bin/hyperkit
  versions:
    kubelet: ""
    controlPlane: ""
